In [7]:
import pandas as pd
from datetime import datetime

In [8]:
# Lista de atendimentos (apenas alguns aqui, complete com os 50 registros)
dados = [
   {"tutor":"Ana","animal":"Cachorro","nome_pet":"Rex1","servico":"Consulta","valor":120,"cidade":"Assis","data":datetime(2026,3,1),"forma_pagamento":"Pix"},
{"tutor":"Bruno","animal":"Gato","nome_pet":"Mimi2","servico":"Vacinação","valor":95,"cidade":"Assis","data":datetime(2026,3,2),"forma_pagamento":"Cartão"},
{"tutor":"Carlos","animal":"Cachorro","nome_pet":"Thor3","servico":"Banho","valor":60,"cidade":"Assis","data":datetime(2026,3,3),"forma_pagamento":"Dinheiro"},
{"tutor":"Daniela","animal":"Ave","nome_pet":"Piu4","servico":"Exame","valor":180,"cidade":"Assis","data":datetime(2026,3,4),"forma_pagamento":"Cartão"},
{"tutor":"Eduardo","animal":"Gato","nome_pet":"Luna5","servico":"Consulta","valor":130,"cidade":"Assis","data":datetime(2026,3,5),"forma_pagamento":"Pix"},
{"tutor":"Fernanda","animal":"Cachorro","nome_pet":"Bob6","servico":"Vacinação","valor":90,"cidade":"Assis","data":datetime(2026,3,6),"forma_pagamento":"Dinheiro"},
{"tutor":"Gabriel","animal":"Coelho","nome_pet":"Pompom7","servico":"Consulta","valor":110,"cidade":"Assis","data":datetime(2026,3,7),"forma_pagamento":"Pix"},
{"tutor":"Helena","animal":"Cachorro","nome_pet":"Mel8","servico":"Cirurgia","valor":820,"cidade":"Assis","data":datetime(2026,3,8),"forma_pagamento":"Cartão"},
{"tutor":"Igor","animal":"Gato","nome_pet":"Simba9","servico":"Banho","valor":55,"cidade":"Assis","data":datetime(2026,3,9),"forma_pagamento":"Cartão"},
{"tutor":"Juliana","animal":"Cachorro","nome_pet":"Nina10","servico":"Consulta","valor":125,"cidade":"Assis","data":datetime(2026,3,10),"forma_pagamento":"Pix"},
{"tutor":"Lucas","animal":"Ave","nome_pet":"Sky11","servico":"Exame","valor":200,"cidade":"Assis","data":datetime(2026,3,11),"forma_pagamento":"Cartão"},
{"tutor":"Mariana","animal":"Gato","nome_pet":"Lili12","servico":"Consulta","valor":135,"cidade":"Assis","data":datetime(2026,3,12),"forma_pagamento":"Pix"},
{"tutor":"Nicolas","animal":"Cachorro","nome_pet":"Bolt13","servico":"Vacinação","valor":100,"cidade":"Assis","data":datetime(2026,3,13),"forma_pagamento":"Dinheiro"},
{"tutor":"Patricia","animal":"Cachorro","nome_pet":"Max14","servico":"Consulta","valor":140,"cidade":"Ourinhos","data":datetime(2026,3,1),"forma_pagamento":"Pix"},
{"tutor":"Rafael","animal":"Gato","nome_pet":"Mia15","servico":"Banho","valor":65,"cidade":"Ourinhos","data":datetime(2026,3,2),"forma_pagamento":"Cartão"},
{"tutor":"Sofia","animal":"Cachorro","nome_pet":"Luna16","servico":"Cirurgia","valor":900,"cidade":"Ourinhos","data":datetime(2026,3,3),"forma_pagamento":"Cartão"},
{"tutor":"Thiago","animal":"Ave","nome_pet":"Blue17","servico":"Exame","valor":170,"cidade":"Ourinhos","data":datetime(2026,3,4),"forma_pagamento":"Pix"},
{"tutor":"Vanessa","animal":"Gato","nome_pet":"Nino18","servico":"Consulta","valor":125,"cidade":"Ourinhos","data":datetime(2026,3,5),"forma_pagamento":"Dinheiro"},
{"tutor":"William","animal":"Cachorro","nome_pet":"Thor19","servico":"Vacinação","valor":95,"cidade":"Ourinhos","data":datetime(2026,3,6),"forma_pagamento":"Pix"},
{"tutor":"Beatriz","animal":"Coelho","nome_pet":"Fluffy20","servico":"Consulta","valor":115,"cidade":"Ourinhos","data":datetime(2026,3,7),"forma_pagamento":"Cartão"},
{"tutor":"Caio","animal":"Cachorro","nome_pet":"Spike21","servico":"Banho","valor":70,"cidade":"Ourinhos","data":datetime(2026,3,8),"forma_pagamento":"Dinheiro"},
{"tutor":"Diego","animal":"Gato","nome_pet":"Tom22","servico":"Consulta","valor":135,"cidade":"Ourinhos","data":datetime(2026,3,9),"forma_pagamento":"Pix"},
{"tutor":"Elisa","animal":"Cachorro","nome_pet":"Mel23","servico":"Exame","valor":210,"cidade":"Ourinhos","data":datetime(2026,3,10),"forma_pagamento":"Cartão"},
{"tutor":"Felipe","animal":"Ave","nome_pet":"Kiwi24","servico":"Consulta","valor":120,"cidade":"Ourinhos","data":datetime(2026,3,11),"forma_pagamento":"Pix"},
{"tutor":"Gisele","animal":"Gato","nome_pet":"Nina25","servico":"Vacinação","valor":85,"cidade":"Ourinhos","data":datetime(2026,3,12),"forma_pagamento":"Dinheiro"},
{"tutor":"Hugo","animal":"Cachorro","nome_pet":"Rex26","servico":"Consulta","valor":150,"cidade":"Ourinhos","data":datetime(2026,3,13),"forma_pagamento":"Cartão"},
{"tutor":"Iris","animal":"Cachorro","nome_pet":"Bob27","servico":"Consulta","valor":110,"cidade":"Pompeia","data":datetime(2026,3,1),"forma_pagamento":"Pix"},
{"tutor":"Joao","animal":"Gato","nome_pet":"Luna28","servico":"Banho","valor":60,"cidade":"Pompeia","data":datetime(2026,3,2),"forma_pagamento":"Dinheiro"},
{"tutor":"Karen","animal":"Cachorro","nome_pet":"Thor29","servico":"Cirurgia","valor":780,"cidade":"Pompeia","data":datetime(2026,3,3),"forma_pagamento":"Cartão"},
{"tutor":"Leo","animal":"Ave","nome_pet":"Sky30","servico":"Exame","valor":160,"cidade":"Pompeia","data":datetime(2026,3,4),"forma_pagamento":"Pix"},
{"tutor":"Marta","animal":"Gato","nome_pet":"Mimi31","servico":"Consulta","valor":120,"cidade":"Pompeia","data":datetime(2026,3,5),"forma_pagamento":"Cartão"},
{"tutor":"Nelson","animal":"Cachorro","nome_pet":"Max32","servico":"Vacinação","valor":90,"cidade":"Pompeia","data":datetime(2026,3,6),"forma_pagamento":"Pix"},
{"tutor":"Olga","animal":"Coelho","nome_pet":"Pompom33","servico":"Consulta","valor":105,"cidade":"Pompeia","data":datetime(2026,3,7),"forma_pagamento":"Dinheiro"},
{"tutor":"Paulo","animal":"Cachorro","nome_pet":"Bolt34","servico":"Banho","valor":75,"cidade":"Pompeia","data":datetime(2026,3,8),"forma_pagamento":"Cartão"},
{"tutor":"Quezia","animal":"Gato","nome_pet":"Simba35","servico":"Consulta","valor":130,"cidade":"Pompeia","data":datetime(2026,3,9),"forma_pagamento":"Pix"},
{"tutor":"Renato","animal":"Cachorro","nome_pet":"Nina36","servico":"Exame","valor":190,"cidade":"Pompeia","data":datetime(2026,3,10),"forma_pagamento":"Cartão"},
{"tutor":"Sara","animal":"Ave","nome_pet":"Blue37","servico":"Consulta","valor":115,"cidade":"Pompeia","data":datetime(2026,3,11),"forma_pagamento":"Pix"},
{"tutor":"Tiago","animal":"Gato","nome_pet":"Lili38","servico":"Vacinação","valor":85,"cidade":"Pompeia","data":datetime(2026,3,12),"forma_pagamento":"Dinheiro"},
{"tutor":"Ursula","animal":"Cachorro","nome_pet":"Rex39","servico":"Consulta","valor":145,"cidade":"Marilia","data":datetime(2026,3,1),"forma_pagamento":"Pix"},
{"tutor":"Vitor","animal":"Gato","nome_pet":"Mia40","servico":"Banho","valor":70,"cidade":"Marilia","data":datetime(2026,3,2),"forma_pagamento":"Cartão"},
{"tutor":"Wesley","animal":"Cachorro","nome_pet":"Thor41","servico":"Cirurgia","valor":870,"cidade":"Marilia","data":datetime(2026,3,3),"forma_pagamento":"Cartão"},
{"tutor":"Xuxa","animal":"Ave","nome_pet":"Piu42","servico":"Exame","valor":175,"cidade":"Marilia","data":datetime(2026,3,4),"forma_pagamento":"Pix"},
{"tutor":"Yara","animal":"Gato","nome_pet":"Luna43","servico":"Consulta","valor":135,"cidade":"Marilia","data":datetime(2026,3,5),"forma_pagamento":"Dinheiro"},
{"tutor":"Zeca","animal":"Cachorro","nome_pet":"Bob44","servico":"Vacinação","valor":100,"cidade":"Marilia","data":datetime(2026,3,6),"forma_pagamento":"Pix"},
{"tutor":"Aline","animal":"Coelho","nome_pet":"Fluffy45","servico":"Consulta","valor":120,"cidade":"Marilia","data":datetime(2026,3,7),"forma_pagamento":"Cartão"},
{"tutor":"Bruna","animal":"Cachorro","nome_pet":"Spike46","servico":"Banho","valor":80,"cidade":"Marilia","data":datetime(2026,3,8),"forma_pagamento":"Dinheiro"},
{"tutor":"Cesar","animal":"Gato","nome_pet":"Tom47","servico":"Consulta","valor":140,"cidade":"Marilia","data":datetime(2026,3,9),"forma_pagamento":"Pix"},
{"tutor":"Dora","animal":"Cachorro","nome_pet":"Mel48","servico":"Exame","valor":220,"cidade":"Marilia","data":datetime(2026,3,10),"forma_pagamento":"Cartão"},
{"tutor":"Enzo","animal":"Ave","nome_pet":"Kiwi49","servico":"Consulta","valor":130,"cidade":"Marilia","data":datetime(2026,3,11),"forma_pagamento":"Pix"},
{"tutor":"Fabio","animal":"Gato","nome_pet":"Nina50","servico":"Vacinação","valor":90,"cidade":"Marilia","data":datetime(2026,3,12),"forma_pagamento":"Dinheiro"},
]

In [9]:
df = pd.DataFrame(dados)
df.head(5)  # mostrar os 5 primeiros registros

,tutor,animal,nome_pet,servico,valor,cidade,data,forma_pagamento
0,Ana,Cachorro,Rex1,Consulta,120,Assis,2026-03-01,Pix
1,Bruno,Gato,Mimi2,Vacinação,95,Assis,2026-03-02,Cartão
2,Carlos,Cachorro,Thor3,Banho,60,Assis,2026-03-03,Dinheiro
3,Daniela,Ave,Piu4,Exame,180,Assis,2026-03-04,Cartão
4,Eduardo,Gato,Luna5,Consulta,130,Assis,2026-03-05,Pix

In [10]:
df.isnull().sum()

tutor              0
animal             0
nome_pet           0
servico            0
valor              0
cidade             0
data               0
forma_pagamento    0
dtype: int64

In [12]:
faturamento_total = df["valor"].sum()
faturamento_total

np.int64(8895)

In [13]:
faturamento_por_cidade = df.groupby("cidade")["valor"].sum().to_dict()
faturamento_por_cidade

{'Assis': 2220, 'Marilia': 2275, 'Ourinhos': 2380, 'Pompeia': 2020}

In [14]:
faturamento_por_servico = df.groupby("servico")["valor"].sum().to_dict()
faturamento_por_servico

{'Banho': 535,
 'Cirurgia': 3370,
 'Consulta': 2655,
 'Exame': 1505,
 'Vacinação': 830}

In [15]:
ticket_medio_geral = df["valor"].mean()
ticket_medio_geral

np.float64(177.9)

In [16]:
ticket_medio_por_cidade = df.groupby("cidade")["valor"].mean().to_dict()
ticket_medio_por_cidade

{'Assis': 170.76923076923077,
 'Marilia': 189.58333333333334,
 'Ourinhos': 183.07692307692307,
 'Pompeia': 168.33333333333334}

In [17]:
servico_mais_lucrativo = max(faturamento_por_servico, key=faturamento_por_servico.get)
servico_mais_lucrativo

'Cirurgia'

In [18]:
cidade_maior_faturamento = max(faturamento_por_cidade, key=faturamento_por_cidade.get)
cidade_maior_faturamento

'Ourinhos'

In [19]:
top_3_atendimentos = df.sort_values(by="valor", ascending=False).head(3).to_dict(orient="records")
top_3_atendimentos

[{'tutor': 'Sofia',
  'animal': 'Cachorro',
  'nome_pet': 'Luna16',
  'servico': 'Cirurgia',
  'valor': 900,
  'cidade': 'Ourinhos',
  'data': Timestamp('2026-03-03 00:00:00'),
  'forma_pagamento': 'Cartão'},
 {'tutor': 'Wesley',
  'animal': 'Cachorro',
  'nome_pet': 'Thor41',
  'servico': 'Cirurgia',
  'valor': 870,
  'cidade': 'Marilia',
  'data': Timestamp('2026-03-03 00:00:00'),
  'forma_pagamento': 'Cartão'},
 {'tutor': 'Helena',
  'animal': 'Cachorro',
  'nome_pet': 'Mel8',
  'servico': 'Cirurgia',
  'valor': 820,
  'cidade': 'Assis',
  'data': Timestamp('2026-03-08 00:00:00'),
  'forma_pagamento': 'Cartão'}]

In [20]:
relatorio = {
    "data_geracao": datetime.now().isoformat(),
    "faturamento_total": float(faturamento_total),
    "faturamento_por_cidade": faturamento_por_cidade,
    "faturamento_por_servico": faturamento_por_servico,
    "ticket_medio_geral": float(ticket_medio_geral),
    "ticket_medio_por_cidade": ticket_medio_por_cidade,
    "servico_mais_lucrativo": servico_mais_lucrativo,
    "cidade_maior_faturamento": cidade_maior_faturamento,
    "top_3_atendimentos": top_3_atendimentos
}

relatorio

{'data_geracao': '2026-03-25T23:50:48.605960',
 'faturamento_total': 8895.0,
 'faturamento_por_cidade': {'Assis': 2220,
  'Marilia': 2275,
  'Ourinhos': 2380,
  'Pompeia': 2020},
 'faturamento_por_servico': {'Banho': 535,
  'Cirurgia': 3370,
  'Consulta': 2655,
  'Exame': 1505,
  'Vacinação': 830},
 'ticket_medio_geral': 177.9,
 'ticket_medio_por_cidade': {'Assis': 170.76923076923077,
  'Marilia': 189.58333333333334,
  'Ourinhos': 183.07692307692307,
  'Pompeia': 168.33333333333334},
 'servico_mais_lucrativo': 'Cirurgia',
 'cidade_maior_faturamento': 'Ourinhos',
 'top_3_atendimentos': [{'tutor': 'Sofia',
   'animal': 'Cachorro',
   'nome_pet': 'Luna16',
   'servico': 'Cirurgia',
   'valor': 900,
   'cidade': 'Ourinhos',
   'data': Timestamp('2026-03-03 00:00:00'),
   'forma_pagamento': 'Cartão'},
  {'tutor': 'Wesley',
   'animal': 'Cachorro',
   'nome_pet': 'Thor41',
   'servico': 'Cirurgia',
   'valor': 870,
   'cidade': 'Marilia',
   'data': Timestamp('2026-03-03 00:00:00'),
   'forma_pagamento': 'Cartão'},
  {'tutor': 'Helena',
   'animal': 'Cachorro',
   'nome_pet': 'Mel8',
   'servico': 'Cirurgia',
   'valor': 820,
   'cidade': 'Assis',
   'data': Timestamp('2026-03-08 00:00:00'),
   'forma_pagamento': 'Cartão'}]}

In [21]:
atendimentos_90_200 = df[(df["valor"] >= 90) & (df["valor"] <= 200)]
atendimentos_90_200.head(10)

,tutor,animal,nome_pet,servico,valor,cidade,data,forma_pagamento
0,Ana,Cachorro,Rex1,Consulta,120,Assis,2026-03-01,Pix
1,Bruno,Gato,Mimi2,Vacinação,95,Assis,2026-03-02,Cartão
3,Daniela,Ave,Piu4,Exame,180,Assis,2026-03-04,Cartão
4,Eduardo,Gato,Luna5,Consulta,130,Assis,2026-03-05,Pix
5,Fernanda,Cachorro,Bob6,Vacinação,90,Assis,2026-03-06,Dinheiro
6,Gabriel,Coelho,Pompom7,Consulta,110,Assis,2026-03-07,Pix
9,Juliana,Cachorro,Nina10,Consulta,125,Assis,2026-03-10,Pix
10,Lucas,Ave,Sky11,Exame,200,Assis,2026-03-11,Cartão
11,Mariana,Gato,Lili12,Consulta,135,Assis,2026-03-12,Pix
12,Nicolas,Cachorro,Bolt13,Vacinação,100,Assis,2026-03-13,Dinheiro

In [23]:
cidades_desejadas = ["Assis", "Ourinhos", "Pompeia", "Marilia"]
df_cidades = df[df["cidade"].isin(cidades_desejadas)]
df_cidades.head(10)

,tutor,animal,nome_pet,servico,valor,cidade,data,forma_pagamento
0,Ana,Cachorro,Rex1,Consulta,120,Assis,2026-03-01,Pix
1,Bruno,Gato,Mimi2,Vacinação,95,Assis,2026-03-02,Cartão
2,Carlos,Cachorro,Thor3,Banho,60,Assis,2026-03-03,Dinheiro
3,Daniela,Ave,Piu4,Exame,180,Assis,2026-03-04,Cartão
4,Eduardo,Gato,Luna5,Consulta,130,Assis,2026-03-05,Pix
5,Fernanda,Cachorro,Bob6,Vacinação,90,Assis,2026-03-06,Dinheiro
6,Gabriel,Coelho,Pompom7,Consulta,110,Assis,2026-03-07,Pix
7,Helena,Cachorro,Mel8,Cirurgia,820,Assis,2026-03-08,Cartão
8,Igor,Gato,Simba9,Banho,55,Assis,2026-03-09,Cartão
9,Juliana,Cachorro,Nina10,Consulta,125,Assis,2026-03-10,Pix